// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gas_curvature_sub_cpp
List gas_curvature_sub_cpp(NumericVector eta, List groups, int p, int q, NumericVector om, NumericMatrix A, NumericMatrix B, int ap, NumericVector s_at, NumericVector c_at, NumericVector g, NumericMatrix Hc, NumericMatrix D3m, List Vs, NumericMatrix seed, int threads);
RcppExport SEXP _modelterms7_gas_curvature_sub_cpp(SEXP etaSEXP, SEXP groupsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP omSEXP, SEXP ASEXP, SEXP BSEXP, SEXP apSEXP, SEXP s_atSEXP, SEXP c_atSEXP, SEXP gSEXP, SEXP HcSEXP, SEXP D3mSEXP, SEXP VsSEXP, SEXP seedSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type om(omSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type ap(apSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s_at(s_atSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c_at(c_atSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Hc(HcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type D3m(D3mSEXP);
    Rcpp::traits::input_parameter< List >::type Vs(VsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gas_curvature_sub_cpp(eta, groups, p, q, om, A, B, ap, s_at, c_at, g, Hc, D3m, Vs, seed, threads));
    return rcpp_result_gen;
END_RCPP
}
// gas_filter_cpp
List gas_filter_cpp(NumericVector eta, List order, int p, int q, double omega, NumericVector a, NumericVector b, NumericMatrix db, double f0, NumericVector df0, IntegerVector i_a, int np, Function score, Function curvature, Nullable<List> fast, int threads);
RcppExport SEXP _modelterms7_gas_filter_cpp(SEXP etaSEXP, SEXP orderSEXP, SEXP pSEXP, SEXP qSEXP, SEXP omegaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dbSEXP, SEXP f0SEXP, SEXP df0SEXP, SEXP i_aSEXP, SEXP npSEXP, SEXP scoreSEXP, SEXP curvatureSEXP, SEXP fastSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< double >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df0(df0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_a(i_aSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< Function >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< Function >::type curvature(curvatureSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type fast(fastSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gas_filter_cpp(eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature, fast, threads));
    return rcpp_result_gen;
END_RCPP
}
// gas_filter_sub_cpp
List gas_filter_sub_cpp(NumericVector eta, List groups, int p, int q, NumericVector om, NumericMatrix A, NumericMatrix B, int np, Function score, Function curvature, Nullable<List> fast, int threads);
RcppExport SEXP _modelterms7_gas_filter_sub_cpp(SEXP etaSEXP, SEXP groupsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP omSEXP, SEXP ASEXP, SEXP BSEXP, SEXP npSEXP, SEXP scoreSEXP, SEXP curvatureSEXP, SEXP fastSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type om(omSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< Function >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< Function >::type curvature(curvatureSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type fast(fastSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gas_filter_sub_cpp(eta, groups, p, q, om, A, B, np, score, curvature, fast, threads));
    return rcpp_result_gen;
END_RCPP
}
// regime_forward_cpp
List regime_forward_cpp(const List& order, const NumericMatrix& LF, const NumericMatrix& SC, const NumericMatrix& dmu, const NumericMatrix& P, const List& dP, const NumericVector& delta, const NumericMatrix& ddelta);
RcppExport SEXP _modelterms7_regime_forward_cpp(SEXP orderSEXP, SEXP LFSEXP, SEXP SCSEXP, SEXP dmuSEXP, SEXP PSEXP, SEXP dPSEXP, SEXP deltaSEXP, SEXP ddeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type order(orderSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type LF(LFSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type SC(SCSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dmu(dmuSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const List& >::type dP(dPSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ddelta(ddeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(regime_forward_cpp(order, LF, SC, dmu, P, dP, delta, ddelta));
    return rcpp_result_gen;
END_RCPP
}
// seg_block_cpp
List seg_block_cpp(int kind, NumericVector xv, NumericVector psi, NumericVector del, NumericVector kap, NumericVector cvec, double lin, bool linear, double lo, double hi);
RcppExport SEXP _modelterms7_seg_block_cpp(SEXP kindSEXP, SEXP xvSEXP, SEXP psiSEXP, SEXP delSEXP, SEXP kapSEXP, SEXP cvecSEXP, SEXP linSEXP, SEXP linearSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type del(delSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kap(kapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< double >::type lin(linSEXP);
    Rcpp::traits::input_parameter< bool >::type linear(linearSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(seg_block_cpp(kind, xv, psi, del, kap, cvec, lin, linear, lo, hi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_modelterms7_gas_curvature_sub_cpp", (DL_FUNC) &_modelterms7_gas_curvature_sub_cpp, 16},
    {"_modelterms7_gas_filter_cpp", (DL_FUNC) &_modelterms7_gas_filter_cpp, 16},
    {"_modelterms7_gas_filter_sub_cpp", (DL_FUNC) &_modelterms7_gas_filter_sub_cpp, 12},
    {"_modelterms7_regime_forward_cpp", (DL_FUNC) &_modelterms7_regime_forward_cpp, 8},
    {"_modelterms7_seg_block_cpp", (DL_FUNC) &_modelterms7_seg_block_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_modelterms7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
