// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gas_filter_cpp
List gas_filter_cpp(NumericVector eta, List order, int p, int q, double omega, NumericVector a, NumericVector b, NumericMatrix db, double f0, NumericVector df0, IntegerVector i_a, int np, Function score, Function curvature);
RcppExport SEXP _modelterms7_gas_filter_cpp(SEXP etaSEXP, SEXP orderSEXP, SEXP pSEXP, SEXP qSEXP, SEXP omegaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dbSEXP, SEXP f0SEXP, SEXP df0SEXP, SEXP i_aSEXP, SEXP npSEXP, SEXP scoreSEXP, SEXP curvatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< double >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df0(df0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_a(i_aSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< Function >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< Function >::type curvature(curvatureSEXP);
    rcpp_result_gen = Rcpp::wrap(gas_filter_cpp(eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature));
    return rcpp_result_gen;
END_RCPP
}
// seg_block_cpp
List seg_block_cpp(int kind, NumericVector xv, NumericVector psi, NumericVector del, NumericVector kap, double lin, bool linear, double floor_w);
RcppExport SEXP _modelterms7_seg_block_cpp(SEXP kindSEXP, SEXP xvSEXP, SEXP psiSEXP, SEXP delSEXP, SEXP kapSEXP, SEXP linSEXP, SEXP linearSEXP, SEXP floor_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type del(delSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kap(kapSEXP);
    Rcpp::traits::input_parameter< double >::type lin(linSEXP);
    Rcpp::traits::input_parameter< bool >::type linear(linearSEXP);
    Rcpp::traits::input_parameter< double >::type floor_w(floor_wSEXP);
    rcpp_result_gen = Rcpp::wrap(seg_block_cpp(kind, xv, psi, del, kap, lin, linear, floor_w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_modelterms7_gas_filter_cpp", (DL_FUNC) &_modelterms7_gas_filter_cpp, 14},
    {"_modelterms7_seg_block_cpp", (DL_FUNC) &_modelterms7_seg_block_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_modelterms7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
