# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gas_filter_cpp <- function(eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature) {
    .Call(`_modelterms7_gas_filter_cpp`, eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature)
}

seg_block_cpp <- function(kind, xv, psi, del, kap, cvec, lin, linear, lo, hi) {
    .Call(`_modelterms7_seg_block_cpp`, kind, xv, psi, del, kap, cvec, lin, linear, lo, hi)
}

