# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gas_curvature_sub_cpp <- function(eta, groups, p, q, om, A, B, ap, s_at, c_at, g, Hc, D3m, Vs, seed, threads = 1L) {
    .Call(`_modelterms7_gas_curvature_sub_cpp`, eta, groups, p, q, om, A, B, ap, s_at, c_at, g, Hc, D3m, Vs, seed, threads)
}

gas_filter_cpp <- function(eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature, fast = NULL, threads = 1L) {
    .Call(`_modelterms7_gas_filter_cpp`, eta, order, p, q, omega, a, b, db, f0, df0, i_a, np, score, curvature, fast, threads)
}

gas_filter_sub_cpp <- function(eta, groups, p, q, om, A, B, np, score, curvature, fast = NULL, threads = 1L) {
    .Call(`_modelterms7_gas_filter_sub_cpp`, eta, groups, p, q, om, A, B, np, score, curvature, fast, threads)
}

regime_forward_cpp <- function(order, LF, SC, dmu, P, dP, delta, ddelta) {
    .Call(`_modelterms7_regime_forward_cpp`, order, LF, SC, dmu, P, dP, delta, ddelta)
}

seg_block_cpp <- function(kind, xv, psi, del, kap, cvec, lin, linear, lo, hi) {
    .Call(`_modelterms7_seg_block_cpp`, kind, xv, psi, del, kap, cvec, lin, linear, lo, hi)
}

